### ISSUE TITLE
OpenMapTiles schema compatibility?

### ISSUE THREAD

**Issue by Bo-Duke** [hyperknot/openfreemap-styles#4]
Hey!

I'm wondering, as the styles you've forked are all based on the OpenMapTiles schema, is compatibility with the schema something that is/will be enforced? (on both those styles and of course openfreemap's tiles).

I understand why it would add complexity to the project's future but having the possibility to use other OpenMapTiles-based styles would be a great thing!

Either way, adding that information in the readme could be interesting

**Comment by hyperknot** [comment]
They are exactly the same. I mean you can use these styles with any OpenMapTiles source and you can use any other OpenMapTiles style with these sources.

I forked them because I wanted to make them consistent with each other (same labels, same borders, etc.). Also I made some visual changes to make them a bit cleaner.

But basically every style which is made for the OpenMapTiles source can be interchanged with each other.

**Comment by Bo-Duke** [comment]
Good to know, it would be understandable if you wanted adjust the tile's schema of the source to better fit your needs as you use your own styles but keeping OpenMapTiles compatibility is a very good thing to have.

Thanks for the quick answer!
